[workspace]
resolver = "2"
members = ["engine", "standalone", "vst", "xtask"]

# Build profiles
[profile.release]
lto = "thin"
strip = "symbols"
panic = "abort"
codegen-units = 1

[profile.dev]
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
